del Felismero_motor_LITE\Felismero_motor\bin /Q /S
del Turan_tester\Turan_tester\bin /Q /S
del Turan_trainer_GUI\Turan_GUI\bin /Q /S
del Turan_SC_minimal\Turan_SC_minimal\bin /Q /S
del Turan_SC\Turan_SC\bin /Q /S
del Turan_creator\Turan_creator\bin /Q /S
del Turan_core\Turan_core\bin /Q /S

del Felismero_motor_LITE\Felismero_motor\obj /Q /S
del Turan_tester\Turan_tester\obj /Q /S
del Turan_trainer_GUI\Turan_GUI\obj /Q /S
del Turan_SC_minimal\Turan_SC_minimal\obj /Q /S
del Turan_SC\Turan_SC\obj /Q /S
del Turan_creator\Turan_creator\obj /Q /S
del Turan_core\Turan_core\obj /Q /S
